-- USUARIOS
CREATE TABLE usuarios
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrasena        VARCHAR(255),
    email             VARCHAR(255) UNIQUE,
    fecha_nacimiento  DATE,
    fecha_registro    DATE,
    hora_notificacion TIME(6),
    nombre            VARCHAR(255),
    telefono          VARCHAR(255),
    verifi_codi       VARCHAR(255),
    verificado        BOOLEAN NOT NULL
);
ALTER TABLE usuarios OWNER TO postgres;

-- VIAJES
CREATE TABLE viajes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion  VARCHAR(255),
    destino      VARCHAR(255),
    fecha_fin    DATE,
    fecha_inicio DATE,
    nombre       VARCHAR(255),
    usuario_id   BIGINT,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);
ALTER TABLE viajes OWNER TO postgres;

-- BILLETES
CREATE TABLE billetes
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255) CHECK (categoria IN ('AVION', 'TREN', 'AUTOBUS', 'BARCO', 'CONCIERTO', 'MUSEO', 'EVENTO', 'OTRO')),
    nombre    VARCHAR(255),
    pdf       BIGINT,
    ubicacion VARCHAR(255),
    viaje_id  BIGINT,
    CONSTRAINT fk_billete_viaje FOREIGN KEY (viaje_id) REFERENCES viajes(id) ON DELETE CASCADE
);
ALTER TABLE billetes OWNER TO postgres;

-- DIAS
CREATE TABLE dias
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana VARCHAR(255) CHECK (dia_semana IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO')),
    fecha      DATE,
    numero_dia INTEGER NOT NULL,
    viaje_id   BIGINT,
    CONSTRAINT fk_dia_viaje FOREIGN KEY (viaje_id) REFERENCES viajes(id) ON DELETE CASCADE
);
ALTER TABLE dias OWNER TO postgres;

-- GASTOS
CREATE TABLE gastos
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad   DOUBLE PRECISION,
    categoria  VARCHAR(255) CHECK (categoria IN ('ALOJAMIENTO', 'COMIDA', 'TRANSPORTE', 'ENTRETENIMIENTO', 'COMPRAS', 'ACTIVIDADES', 'OTROS')),
    es_ingreso BOOLEAN NOT NULL,
    fecha      DATE,
    titulo     VARCHAR(255),
    id_viaje   BIGINT,
    CONSTRAINT fk_gasto_viaje FOREIGN KEY (id_viaje) REFERENCES viajes(id) ON DELETE CASCADE
);
ALTER TABLE gastos OWNER TO postgres;

-- ITINERARIO
CREATE TABLE itinerario
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actividad             VARCHAR(255),
    aparece_en_itinerario BOOLEAN NOT NULL,
    categoria             VARCHAR(255) CHECK (categoria IN ('MUSEO', 'IGLESIA', 'PARQUE', 'MONUMENTO', 'EVENTO', 'OTROS')),
    duracion              VARCHAR(255),
    esta_en_ruta          BOOLEAN NOT NULL,
    foto                  BIGINT,
    hora                  TIME(6),
    latitud               VARCHAR(255),
    longitud              VARCHAR(255),
    medio_transporte      VARCHAR(255) CHECK (medio_transporte IN ('ANDANDO', 'BICICLETA', 'COCHE', 'AUTOBUS', 'TREN', 'METRO', 'TAXI', 'BARCO', 'TRANVIA', 'OTRO') OR NULL),
    billete_id            BIGINT UNIQUE,
    dia_id                BIGINT,
    CONSTRAINT fk_itinerario_billete FOREIGN KEY (billete_id) REFERENCES billetes(id) ON DELETE SET NULL,
    CONSTRAINT fk_itinerario_dia FOREIGN KEY (dia_id) REFERENCES dias(id) ON DELETE CASCADE

);
ALTER TABLE itinerario OWNER TO postgres;

-- HORARIO
CREATE TABLE horario
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia           VARCHAR(255) CHECK (dia IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO')),
    hora_fin      TIME(6),
    hora_inicio   TIME(6),
    is_closed     BOOLEAN NOT NULL,
    itinerario_id BIGINT,
    CONSTRAINT fk_horario_itinerario FOREIGN KEY (itinerario_id) REFERENCES itinerario(id) ON DELETE CASCADE
);
ALTER TABLE horario OWNER TO postgres;

-- MALETAS
CREATE TABLE maletas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255),
    peso        DOUBLE PRECISION,
    tipo_maleta VARCHAR(255) CHECK (tipo_maleta IN ('MALETA_FACTURADA', 'MALETA_CABINA', 'MALETIN_PORTATIL', 'MOCHILA', 'BOLSO', 'OTRO')),
    viaje_id    BIGINT,
    CONSTRAINT fk_maleta_viaje FOREIGN KEY (viaje_id) REFERENCES viajes(id) ON DELETE CASCADE
);
ALTER TABLE maletas OWNER TO postgres;

-- OBJETOS MALETA
CREATE TABLE objetos_maleta
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad    INTEGER NOT NULL,
    categoria   VARCHAR(255) CHECK (categoria IN ('ROPA', 'ELECTRONICA', 'HIGIENE', 'DOCUMENTOS', 'ACCESORIOS', 'OTROS')),
    is_selected BOOLEAN NOT NULL,
    nombre      VARCHAR(255),
    maleta_id   BIGINT,
    CONSTRAINT fk_objeto_maleta FOREIGN KEY (maleta_id) REFERENCES maletas(id) ON DELETE CASCADE
);
ALTER TABLE objetos_maleta OWNER TO postgres;

-- NOTIFICACIONES
CREATE TABLE notificaciones
(
    id_notificacion   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado            VARCHAR(255) NOT NULL CHECK (estado IN ('PENDIENTE', 'ENVIADA', 'FALLIDA')),
    fecha_creacion    TIMESTAMP(6) NOT NULL,
    fecha_envio       TIMESTAMP(6) NOT NULL,
    mensaje           TEXT NOT NULL,
    tipo_notificacion VARCHAR(255) NOT NULL CHECK (tipo_notificacion IN ('RECORDATORIO', 'ALERTA', 'INFORMACION')),
    id_usuario        BIGINT NOT NULL,
    id_viaje          BIGINT NOT NULL,
    CONSTRAINT fk_notificacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_notificacion_viaje FOREIGN KEY (id_viaje) REFERENCES viajes(id) ON DELETE CASCADE
);
ALTER TABLE notificaciones OWNER TO postgres;

-- NOTIFICACION DESCARTADA
CREATE TABLE notificacion_descartada
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha      DATE,
    usuario_id BIGINT,
    viaje_id   BIGINT,
    CONSTRAINT fk_descartada_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_descartada_viaje FOREIGN KEY (viaje_id) REFERENCES viajes(id) ON DELETE CASCADE
);
ALTER TABLE notificacion_descartada OWNER TO postgres;
