CREATE TABLE usuarios
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrasena        VARCHAR(255),
    email             VARCHAR(255) UNIQUE,
    fecha_nacimiento  DATE,
    fecha_registro    DATE,
    hora_notificacion TIME(6),
    nombre            VARCHAR(255),
    telefono          VARCHAR(255),
    verifi_codi       VARCHAR(255),
    verificado        BOOLEAN NOT NULL
);

ALTER TABLE usuarios OWNER TO postgres;

CREATE TABLE viajes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion  VARCHAR(255),
    destino      VARCHAR(255),
    fecha_fin    DATE,
    fecha_inicio DATE,
    nombre       VARCHAR(255),
    usuario_id   BIGINT,
    CONSTRAINT fkgoq4qi4euu9uov10eyjfct3uf FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

ALTER TABLE viajes OWNER TO postgres;

CREATE TABLE billetes
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255) CHECK (categoria IN ('AVION', 'TREN', 'AUTOBUS', 'BARCO', 'CONCIERTO', 'MUSEO', 'EVENTO', 'OTRO')),
    nombre    VARCHAR(255),
    pdf       BIGINT,
    ubicacion VARCHAR(255),
    viaje_id  BIGINT,
    CONSTRAINT fkni6jc1ohy28mvl4mx2f3ym0au FOREIGN KEY (viaje_id) REFERENCES viajes(id) ON DELETE SET NULL
);

ALTER TABLE billetes OWNER TO postgres;

CREATE TABLE dias
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana VARCHAR(255) CHECK (dia_semana IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO')),
    fecha      DATE,
    numero_dia INTEGER NOT NULL,
    viaje_id   BIGINT,
    CONSTRAINT fkton57f6hxca3au30s5xq9xk0b FOREIGN KEY (viaje_id) REFERENCES viajes(id) ON DELETE SET NULL
);

ALTER TABLE dias OWNER TO postgres;

CREATE TABLE gastos
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad   DOUBLE PRECISION,
    categoria  VARCHAR(255) CHECK (categoria IN ('ALOJAMIENTO', 'COMIDA', 'TRANSPORTE', 'ENTRETENIMIENTO', 'COMPRAS', 'ACTIVIDADES', 'OTROS')),
    es_ingreso BOOLEAN NOT NULL,
    fecha      DATE,
    titulo     VARCHAR(255),
    id_viaje   BIGINT,
    CONSTRAINT fkk3fs6fs3snsfrlngnu2tvyjkw FOREIGN KEY (id_viaje) REFERENCES viajes(id) ON DELETE SET NULL
);

ALTER TABLE gastos OWNER TO postgres;

CREATE TABLE itinerario
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actividad             VARCHAR(255),
    aparece_en_itinerario BOOLEAN NOT NULL,
    categoria             VARCHAR(255) CHECK (categoria IN ('MUSEO', 'IGLESIA', 'PARQUE', 'MONUMENTO', 'EVENTO', 'OTROS')),
    duracion              VARCHAR(255),
    esta_en_ruta          BOOLEAN NOT NULL,
    foto                  BIGINT,
    hora                  TIME(6),
    latitud               VARCHAR(255),
    longitud              VARCHAR(255),
    medio_transporte      VARCHAR(255) CHECK (medio_transporte IN ('ANDANDO', 'BICICLETA', 'COCHE', 'AUTOBUS', 'TREN', 'METRO', 'TAXI', 'BARCO', 'TRANVIA', 'OTRO')),
    billete_id            BIGINT UNIQUE,
    dia_id                BIGINT,
    CONSTRAINT fk7id14h2sjfmvyt2soxvb7gfhe FOREIGN KEY (billete_id) REFERENCES billetes(id) ON DELETE SET NULL,
    CONSTRAINT fktjh97wmv7qkgi7nsp0f99fuds FOREIGN KEY (dia_id) REFERENCES dias(id) ON DELETE SET NULL
);

ALTER TABLE itinerario OWNER TO postgres;

CREATE TABLE horario
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia           VARCHAR(255) CHECK (dia IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO')),
    hora_fin      TIME(6),
    hora_inicio   TIME(6),
    is_closed     BOOLEAN NOT NULL,
    itinerario_id BIGINT,
    CONSTRAINT fk6ltjqqv6q7xwql00yu68nidut FOREIGN KEY (itinerario_id) REFERENCES itinerario(id) ON DELETE CASCADE
);

ALTER TABLE horario OWNER TO postgres;

CREATE TABLE maletas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255),
    peso        DOUBLE PRECISION,
    tipo_maleta VARCHAR(255) CHECK (tipo_maleta IN ('MALETA_FACTURADA', 'MALETA_CABINA', 'MALETIN_PORTATIL', 'MOCHILA', 'BOLSO', 'OTRO')),
    viaje_id    BIGINT,
    CONSTRAINT fkjqnr9yirkbkk67asgw7ef5pan FOREIGN KEY (viaje_id) REFERENCES viajes(id) ON DELETE SET NULL
);

ALTER TABLE maletas OWNER TO postgres;

CREATE TABLE notificaciones
(
    id_notificacion   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado            VARCHAR(255) NOT NULL CHECK (estado IN ('PENDIENTE', 'ENVIADA', 'FALLIDA')),
    fecha_creacion    TIMESTAMP(6) NOT NULL,
    fecha_envio       TIMESTAMP(6) NOT NULL,
    mensaje           TEXT NOT NULL,
    tipo_notificacion VARCHAR(255) NOT NULL CHECK (tipo_notificacion IN ('RECORDATORIO', 'ALERTA', 'INFORMACION')),
    id_usuario        BIGINT NOT NULL,
    id_viaje          BIGINT NOT NULL,
    CONSTRAINT fkrr0ikjdv4qycj44q3lohskm4k FOREIGN KEY (id_usuario) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fkte6629sldlu511sveb82x7axn FOREIGN KEY (id_viaje) REFERENCES viajes(id) ON DELETE CASCADE
);

ALTER TABLE notificaciones OWNER TO postgres;

CREATE TABLE objetos_maleta
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad    INTEGER NOT NULL,
    categoria   VARCHAR(255) CHECK (categoria IN ('ROPA', 'ELECTRONICA', 'HIGIENE', 'DOCUMENTOS', 'ACCESORIOS', 'OTROS')),
    is_selected BOOLEAN NOT NULL,
    nombre      VARCHAR(255),
    maleta_id   BIGINT,
    CONSTRAINT fkmsje9u3qj13miqu046v6qft87 FOREIGN KEY (maleta_id) REFERENCES maletas(id) ON DELETE CASCADE
);

ALTER TABLE objetos_maleta OWNER TO postgres;

CREATE TABLE notificacion_descartada
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha      DATE,
    usuario_id BIGINT,
    viaje_id   BIGINT
);

ALTER TABLE notificacion_descartada OWNER TO postgres;
